version: '3'

services:
  db:
    image: postgres
    container_name: ps01
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8080:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - pgdata:/var/lib/postgresql/data/
    depends_on:
      - web
  web:
    build: .
    image: bazango_img
    container_name: web01
    command: "gunicorn bazango.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
    depends_on:
      - db
    expose:
      - "8000"

volumes:
  pgdata:
